FROM ubuntu:latest

COPY setup.sh /usr/
COPY entrypoint.sh /usr/
RUN mkdir /usr/conf
COPY conf/* /usr/conf/
RUN chmod +x /usr/setup.sh
RUN chmod +x /usr/entrypoint.sh
RUN /usr/setup.sh

ENV SPARK_HOME /usr/spark-2.2.1-bin-hadoop2.7
ENV SPARK_CONF_DIR /usr/conf
ENV LIVY_CONF_DIR /usr/conf
EXPOSE 8998
EXPOSE 8080
EXPOSE 4040

#ENTRYPOINT /usr/entrypoint.sh
